#!/bin/bash
IFS=$'\n\t'

# Config part ========================================
version='v0.1.0'
describe=1
tmp_output=$(mktemp)

# Functions ========================================
function zen() {
    kubectl \
        --as admin \
        --as-group system:masters \
        --context sell-dmz-staging \
        --namespace $service \
        "$@"
}

function describe() {
    ## Determine what we want to describe eg.: 'deployment' || 'pod'
    kind_of_describe=$1

    echo $tmp_output
    i=0
    while read line; do
        printf "%u. %10s\n" $i "$line"
        i=$(( i + 1 ))
    done < $tmp_output

    echo "What do you want to describe?"
    read ans
    # [[ $ans -gt i ]] && echo "Wrong number"; exit 1 
    choice=$(head -n $(( ans + 1 )) $tmp_output | tail -n 1)
    name=$( echo $choice | cut -f 1 -w)
    kubectl --context sell-dmz-staging --namespace $service describe $kind_of_describe $name
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
    case $1 in
        -V | --version )
        echo $version
        exit
        ;;
        -d | --describe )
        shift; describe=0
        ;;
        *) echo "There is no such an option"; exit 1
    esac
done

service=$1
shift

if [[ $describe -eq 0 ]]; then
    zen "$@" > $tmp_output
    describe ${2%s}
else
    zen "$@"
fi
